Admin review
jpmagido/la-mission-parfaite pull request #4
Opened 2021-10-25 13:42 UTC by Seven-dev7

Add : 
AdminReview model
Associations, validates, enum
Spec, model
Factory

Trello : 
https://trello.com/c/1NpNdqob/35-validation-par-ladmin

2021-10-25 21:55 UTC, jpmagido commented on app/controllers/administration/admin_messages_controller.rb
> +  class AdminMessagesController < BaseController
J'ai mis AdminMessage mais c'est AdminReview pour garder la logique

2021-10-25 21:56 UTC, jpmagido commented on app/models/admin_review.rb
> +  validates :comment, length: { in: 2..100 }
2..1000

2021-10-25 21:57 UTC, jpmagido commented on app/views/administration/admin_messages/_search_filter.html.erb
> +<% end %>
attention aux endline, y'en a plusieurs ;)

2021-10-25 21:58 UTC, jpmagido commented on config/locales/en.yml
> +      todo: "A Faire"
J'aime bien, après on a pas d'anglophones sur le site, du coup je pense pas faire de trad.
Ou en patois peut-être ^^

2021-10-25 21:59 UTC, jpmagido commented on db/migrate/20211025122240_create_admin_reviews.rb
> +      t.string :last_name
ajoutes moi des `null: false` sur first_name, last_name stp

2021-10-25 22:00 UTC, jpmagido commented on db/seeds.rb
> +  AdminReview.destroy_all
Il est déjà dans l'autre méthode (l:64)

2021-10-26 03:34 UTC, Seven-dev7 commented on app/controllers/administration/admin_messages_controller.rb
> +  class AdminMessagesController < BaseController
Je trouvais ça bizarre mais ça faisait partie des questions que je voulais te poser

2021-10-26 03:34 UTC, Seven-dev7 commented on app/models/admin_review.rb
> +  validates :comment, length: { in: 2..100 }
Yes

2021-10-26 03:35 UTC, Seven-dev7 commented on config/locales/en.yml
> +      todo: "A Faire"
J étais partis pour faire la trad en Fr des values de l enum avec i18n_scope de la gem enumerize, mais je suis retourné sur l enum classique de Rails et faut que je delete ce que j avais commencé

2021-10-26 03:35 UTC, Seven-dev7 commented on db/migrate/20211025122240_create_admin_reviews.rb
> +      t.string :last_name
Ok

2021-10-26 03:35 UTC, Seven-dev7 commented on db/seeds.rb
> +  AdminReview.destroy_all
J ai pas fini,

2021-10-26 04:10 UTC, Seven-dev7 commented on app/views/administration/admin_messages/_search_filter.html.erb
> +<% end %>
Yes

2021-10-26 06:55 UTC, Seven-dev7 commented on app/controllers/administration/admin_messages_controller.rb
> +  class AdminMessagesController < BaseController
Du coup je mets AdminReviewsController au lieu d ' AdminMessagesController et je changes le noms des routes et les dossiers?

2021-10-26 07:09 UTC, Seven-dev7 commented on config/locales/en.yml
> +      todo: "A Faire"
en patois...
Enfoiré

2021-10-26 07:48 UTC, Seven-dev7 commented on app/controllers/administration/admin_messages_controller.rb
> +  class AdminMessagesController < BaseController
fait

2021-10-26 12:56 UTC, jpmagido commented on app/views/administration/admin_reviews/_list.html.erb
> +<p class="card-text">Email : <%= admin_review.admin.email %></p>
`admin_review.email` c'est l'email de la personne qui a fait la demande qu'il faut afficher ;)

2021-10-26 13:00 UTC, jpmagido commented on app/views/administration/admin_reviews/new.html.erb
> +<h1>New Admin Reviews</h1>
a priori on va pas mettre de view new.

ce qui va être fait dans une prochaine carte c'est:
exemple: Si l'admin clique sur un Restaurant qui n'a pas encore été review ca va créer une review sauf si une review existe déjà pour ce même admin.

2021-10-26 13:01 UTC, jpmagido commented on app/views/administration/admin_reviews/show.html.erb
> +<h2 class="text-center"> <%= admin_review.first_name %> <%= admin_review.last_name %>(<%= admin_review.status %>)</h2>
Si tu peux préciser que c'est le nom du visiteur c'est cool

un truc du genre: 'demande de validation par: <%= admin_review.first_name %> <%= admin_review.last_name %>

2021-10-26 13:01 UTC, jpmagido commented on app/views/layouts/application.html.erb
> +    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
a gérer

2021-10-26 13:02 UTC, jpmagido commented on config/locales/en.yml
> +      todo: "A Faire"
Oui ok je vois, j'avais pas pensé aux enum.
Alors simplement un fichier FR c'est très bien ;)

2021-10-26 13:03 UTC, jpmagido commented on config/routes.rb
> +    resources :admin_reviews
only: [:index, :edit, :update, :show]

2021-10-26 13:04 UTC, jpmagido commented on db/migrate/20211025122240_create_admin_reviews.rb
> +      t.text :comment
On peut surement faire un truc du genre: 
t.text visitor_comment
t.text admin_comment

T'en penses quoi ?

2021-10-26 13:05 UTC, jpmagido commented on spec/factories.rb
> +    association :reviewable, factory: [:housing, :restaurant]
y'a pas besoin de faire `[:housing, :restaurant].sample` ?

2021-10-26 13:06 UTC, jpmagido commented on spec/requests/administration/admin_reviews_spec.rb
> +        expect(admin_review.status).to eq('todo')
Il manque le get ^^
Si tu trouves pas on peut le faire ensemble

2021-10-27 05:58 UTC, Seven-dev7 commented on spec/requests/administration/admin_reviews_spec.rb
> +        expect(admin_review.status).to eq('todo')
ouais lol, j'ai essayé de le faire (1ere fois), mais je sentais qu'il manquit quelque chose.
Je veux bien :D

2021-10-27 05:59 UTC, Seven-dev7 commented on spec/factories.rb
> +    association :reviewable, factory: [:housing, :restaurant]
Je penses que meme ["Housing", "Restaurant"].sample aussi du coup non?
aprés j'ai fouillé sur le net et j'ai trouvé l argument factory
Ca vaut quoi a ton avis?

2021-10-27 05:59 UTC, Seven-dev7 commented on config/routes.rb
> +    resources :admin_reviews
yes

2021-10-27 06:00 UTC, Seven-dev7 commented on app/views/administration/admin_reviews/_list.html.erb
> +<p class="card-text">Email : <%= admin_review.admin.email %></p>
Oui c'est vrai, je sais pas pk j ai mis ca....

2021-10-28 22:48 UTC, jpmagido commented on spec/factories.rb
> +    association :reviewable, factory: [:housing, :restaurant]
Je sais pas, je crois qu'il faut passer des symbols.
Si ca fonctionne comme ça, ça me va ;)

2021-10-28 22:48 UTC, jpmagido requested changes
a finir ;)

2021-11-11 23:43 UTC, merged